// Star fields behind the globe. Cesium-free, because the url schema and the Map menu need the list too.

/**
 * Named for catalogue and cube face size, ordered by cost. `Tycho1K` ships with Cesium
 * and always exists. The DeepStar cuts (NASA SVS Deep Star Maps 2020) are generated by
 * `pnpm update-starmap`, so a checkout can lack them.
 *
 * Resident memory (no sky box mipmaps): ~25 MB per 1K map, ~100 MB for 2K. Download:
 * 0.85, 1.3 and 6.4 MB. The generated faces are WebP because JPEG spends its error
 * budget on a near-black sky (see `FORMAT` in scripts/starmap/cubemap.py).
 */
export const STAR_MAPS = ["Tycho1K", "DeepStar1K", "DeepStar2K"] as const;

export type StarMapName = (typeof STAR_MAPS)[number];

/** The map that cannot be missing, and so the fallback everywhere. */
export const BUILTIN_STAR_MAP: StarMapName = "Tycho1K";

interface StarMapAsset {
  /** Path stem for the six faces (`_px.webp` and friends). */
  prefix: string;
  /** The command the missing-asset warning suggests. */
  recovery: string;
}

const GENERATOR = "pnpm update-starmap";

// `Tycho1K` is absent: Cesium resolves its faces through `buildModuleUrl`, and the path moves
// with the Cesium version. The others can be missing, so `CesiumController.applyStarMap` fetches them itself.
const ASSETS: Partial<Record<StarMapName, StarMapAsset>> = {
  DeepStar1K: { prefix: "data/starmap/deepstar_2020_1024", recovery: GENERATOR },
  DeepStar2K: { prefix: "data/starmap/deepstar_2020_2048", recovery: GENERATOR },
};

/** Named the way Cesium's `SkyBox` wants them. */
export interface StarMapSources {
  positiveX: string;
  negativeX: string;
  positiveY: string;
  negativeY: string;
  positiveZ: string;
  negativeZ: string;
}

/** `undefined` for Cesium's own faces. */
export function starMapSources(name: string): StarMapSources | undefined {
  const asset = ASSETS[name as StarMapName];
  if (asset === undefined) {
    return undefined;
  }
  const { prefix } = asset;
  return {
    positiveX: `${prefix}_px.webp`,
    negativeX: `${prefix}_mx.webp`,
    positiveY: `${prefix}_py.webp`,
    negativeY: `${prefix}_my.webp`,
    positiveZ: `${prefix}_pz.webp`,
    negativeZ: `${prefix}_mz.webp`,
  };
}

export function starMapRecovery(name: string): string | undefined {
  return ASSETS[name as StarMapName]?.recovery;
}

// One probe per map for the life of the page; the menu asks on every render.
const probes = new Map<string, Promise<boolean>>();

/**
 * Narrows the menu only; the url vocabulary stays wide and sceneSync falls back to
 * BUILTIN_STAR_MAP.
 *
 * A ranged `GET`, not a `HEAD`: the Cache API ignores non-GET requests, and a cache
 * hit returns the whole stored face, which keeps the offline case working. The
 * content type is checked because an SPA fallback answers 200 with `index.html`.
 * A network error counts as available: no answer is not evidence of absence.
 */
export async function starMapAvailable(name: string): Promise<boolean> {
  const sources = starMapSources(name);
  if (sources === undefined) {
    return (STAR_MAPS as readonly string[]).includes(name);
  }
  let probe = probes.get(name);
  if (probe === undefined) {
    probe = fetch(sources.positiveX, { headers: { Range: "bytes=0-0" } })
      .then((response) => response.ok && (response.headers.get("content-type") ?? "").startsWith("image/"))
      .catch(() => true);
    probes.set(name, probe);
  }
  return probe;
}

/** In `STAR_MAPS` order. */
export async function availableStarMaps(): Promise<StarMapName[]> {
  const present = await Promise.all(STAR_MAPS.map((name) => starMapAvailable(name)));
  return STAR_MAPS.filter((_, index) => present[index]);
}
