# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    increment_build_number(build_number: latest_testflight_build_number + 1)
    build_app(scheme: "satvis")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
  lane :screenshots do
    capture_screenshots(scheme: "satvisUITests",
        clear_previous_screenshots: true,
        clean: true,
        concurrent_simulators: false,
        erase_simulator: true,
        reinstall_app: true
        )
    #upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
end
